name: Deploy front

on:
  push:
    branches: [ "main" ]
    paths:
      - frontend/**
  pull_request:
    branches: [ "main" ]
    paths:
      - frontend/**

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ./DynamicAvatar/
          git pull
          cd ../Donft-mvp/
          docker compose build --force-rm --no-cache donft_inch
          docker compose up -d